### ISSUE TITLE
Fix Time on Results Page

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#147]
As a person submitting tests, I want to see the time that a test was submitted, so I can easily  confirm the test I submitted is showing up in the results page or find a specific past test result.

Update Results page to do a better job of showing time with the results.

- clean up date handling in the API

In priority order:
- [x] Sort results from most recent to least recent
- [x] Show results in the user's local timezone. Or hardcode to mountain time- that works for now
- [x] Show results with a time stamp (HH:MM am/pm) next to the date - no seconds

**Comment by dmethvin-gov** [comment]
@aliciabeckett-gov This will require changes on both frontend and backend because currently the database only stores the date and not the time. We'll need to change the way the date is stored, which will break existing data most likely, and then I can parse and reformat to local time in the frontend.

Another question is exactly when that date and time should be. Right now it is the time the backend received the information from the frontend. It is not the date the time the test was administered or the time the result was read.

**Comment by dmethvin-gov** [comment]
PR in https://github.com/CDCgov/prime-data-input-client/pull/210

**Comment by aliciabeckett-gov** [comment]
Missed the question (sorry about that) but just looked at the results page and the timezone looks great!

**Comment by dmethvin-gov** [comment]
@aliciabeckett-gov Great! Yeah, the question about what this time represents would need to be addressed elsewhere, but for now you know it's the time when they submit the result to the backend. If people are batching these in their workflow and entering them much later it might not be close to the time they tested.

**Comment by aliciabeckett-gov** [comment]
That's perfect!
