### ISSUE TITLE
Support multiple organizations/facilities

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#149]
Be able to have more than one facility use the application. We had to do some things to get the app out the door, and now that we got there it's time to go back and add support for multiple testing sites so we can expand beyond the first testing site.

We need to have:
-Multiple organizations
-Patients/People assigned to an organization
-Users and their accounts/roles assigned to an organization
-Organizations cannot see each other's data

**Comment by benwarfield-usds** [comment]
Features we've talked about that have some relationship to this, and should be concretely placed in or out of scope (with light editorializing because this conversation can get abstract quickly):

* logged-in patient experience (seems like a definite no)
* multiple facilities per org (seems like a probable yes)
* self-service user management (hoping this is still a no) and enrollment (clearly a no IMO)
* sharing provider information between facilities (a little bit of an oddball, but maybe worth discussing)
* multiple roles within an organization, to differentiate administrative functions from data entry (seems implied yes, but actually doesn't have to be)

**Comment by aliciabeckett-gov** [comment]
Here's my thoughts
> 
> * logged-in patient experience (seems like a definite no)
No this is a different epic coming later. It's being designed and user tested now

> * multiple facilities per org (seems like a probable yes)
This would be great to have at the same time. If I can only have one I'd choose multiple orgs, but they really are both needed.

> * self-service user management (hoping this is still a no) and enrollment (clearly a no IMO)
Not any time soon

> * sharing provider information between facilities (a little bit of an oddball, but maybe worth discussing)
Nope, we can get duplicate records, it doesn't really matter.

> * multiple roles within an organization, to differentiate administrative functions from data entry (seems implied yes, but actually doesn't have to be)
This is coming soon in a different epic. There's still user research being done on it.

**Comment by benwarfield-usds** [comment]
Sounds good!

So, the obvious things we're going to have to clarify about facilities are

* the relationship of patients to facilities
* the relationship of users to facilities (and possibly to roles at facilities)
* under what circumstances you can read data from other facilities within the same organization, and under what circumstances you _should_ read such data (e.g. seeing other facilities' patient lists or results)

**Comment by aliciabeckett-gov** [comment]
@hmyers-cms and @katiealoisi have a lot of these answers. If you have a chance it would be good to sync with them today.

**Comment by willusds** [comment]
We're full on integrating this and have broken it out into many tickets so closing this epic.

**Comment by benwarfield-usds** [comment]
Although, apparently not quite enough tickets. 😆
