### ISSUE TITLE
Schedule regular touchpoint between engineering and design

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-central#16]
Lead: Pete

**Comment by willusds** [comment]
Does the grooming session help with this? Or is there another piece we should add? @pete-usds

**Comment by pete-gov** [comment]
@sharmaneil is the primer driver here, so roping him in for thoughts.

**Comment by willusds** [comment]
Sure, not trying to add more meetings for meetings sake, I thought this was something we said we wanted out of Sprint planning. As long as we aren't getting into a dangerous game of telephone with 1:1s and agree to post convos in the open respective Teams/Slack channels so folks can follow and respond if they have feedback, that sounds fine.

**Comment by pete-gov** [comment]
To clarify - right now @sharmaneil  is the only engineer working on the front end, and @switzersc-usds is the only other engineer working on stuff related to that. I'm just a peanut gallery, I shouldn't have expressed an opinion earlier - I'm 100% deferring to Neil & Shelby.

**Comment by pete-gov** [comment]
Gonna call this as done in the current PRIME TIME meetings for now - let's revisit after milestone 1 if we want to change this!

**Comment by sharmaneil** [comment]
Thanks! Agree on closing it

Just to comment (missed seeing this before the slack notifications):
- I don't know if we need a *regular* touchpoint. Ad hoc touch points should be fine. 
- I've been communicating with design via comments on invision so far. This works, but is insufficient. The mocks have been changing a lot, and a lot communication gaps would be closed as the designs solidify. 
- Design already has several issues open which I periodically comment on. 
- Right now, none of the frontend work is tracked in github since there's a lot of it and I don't want to deal with managing issues. Once the app is somewhat fleshed out, we should start converting the missing/broken features into issues, which would help with async communication between eng+design. 
- It would be nice to onboard a designer into the code base to do some of the style work and React, but I'm waiting for the codebase to settle a bit before jumping into that.
