### ISSUE TITLE
Discuss and plan for API versioning

### ISSUE THREAD

**Issue by pete-gov** [CDCgov/prime-central#35]
As **engineers** planning for long term health of this product, we need a plan for **how to handle versioning in the API** before we get too deep in implementing it.

(At a very high level, versioning allows us to change the way the API works or add/remove features while ensuring backwards compatibility with older clients)

<img width="356" alt="Screen Shot 2020-10-07 at 12 03 22 PM" src="https://user-images.githubusercontent.com/51794651/95356838-1deaab80-0895-11eb-818b-ac227eaa84c0.png">

**Comment by switzersc-usds** [comment]
Getting the conversation started... 

There are lots of ways to version. We've got to decide *who* we're versioning for, *what* we're versioning, *how* we're versioning it, *when* we version, *why* we version, and *how* we communicate changes.

*Who* cares about our API versioning? Right now it's just ourselves, with a focus on the Data Input Client application that will be sending and receiving data from this API. This makes the *how* of communication pretty straightforward. However, it's likely that after MVP, as we scale, we will want to receive data from other apps. Perhaps that integration wouldn't happen with the Data Input API but instead with the Data Hub. Maybe the Data Input API grows to become the foundation for the Data Hub, or maybe it doesn't. I think let's keep the two ideas separate for now and just have this conversation for the Data Input API. 

The other *who* we're concerned with is who this API sends data to. The Data Input product use case includes sending the patient and test information to Public Health Departments (PHDs). As an MVP, maybe this this just means the API exports a CSV and then that is sent electronically to PHDs (e.g. with SFTP or email to begin with), but eventually this will need to happen via API (e.g. HL7, FHIR, etc). For the MVP, the CSV export could be considered part of the API. Does the CSV need to be versioned? For post-MVP, as we improve sending data to PHDs, I think this starts to get into Data Hub territory. If we're treating this API and the Hub separately as two services that interact with each other, then perhaps the versioning of APIs used to send data to PHDs can primarily fall into the scope of the Hub. Then, for the purposes of the Data Input API, we really only have to worry about internal project users from the Client app and the CSV export (MVP) and Data Hub (post-MVP). 

Lots more to discuss re: versioning (and I'll post some thoughts in separate comments to keep things somewhat organized by topic, but I want to make sure we're all on the same page about who's consuming this API first before we talk about versioning strategies best for those users and use cases.

**Comment by pete-gov** [comment]
Agree with all. Adding some thoughts on a couple points:

1. The line between Data Input and Data Hub is likely where data leaves the Data Input data store. At that point it would be processed by Data Hub systems to be routed to a PHD. 
    * Data Input Prototype having a CSV export makes sense - which would then use a Data Hub Prototype to translate to something else _(edit: or rather, the data hub prototype would use the underlying data to translate the raw data to something else)_
    * We talked about this when initially shifting resources to Data Input (that it would lead to Data Hub Prototype) but not sure if Product has agreed anywhere on this philosophy

2. "Who" on the Data Hub side could be any client, diverse clients, and breaking changes will break their reporting systems. But on the Data Input side, I think the "who" might just be whoever is writing the webapp front end?
    * Is there a "who" use case for someone to automate uploading CSVs etc. via an API to Input? 

3. "Does the CSV need to be versioned" - this is a huge catch, I think yes, especially if we start with some fields then start adding critical fields for different pilots and growing from there.


*edit to be clear:* added some thoughts to support with maybe a slightly different perspective, re-hashing some of the same stuff.

> Then, for the purposes of the Data Input API, we really only have to worry about internal project users from the Client app and the CSV export (MVP) and Data Hub (post-MVP).

100. This.

**Comment by benwarfield-usds** [comment]
I was assuming that we were talking about the client-facing transactional APIs here, so I'm going to start by talking about them

* the _who_ is anybody we want to be able to deploy our front end—that could be just us, but we could have multiple (branded) front ends feeding the same multi-tenant API back end, and in that case we would want to be able to know who was still deploying the old version
* the _why_ seems fairly straightforward to me, unless I'm missing something: we want to be able to do asynchronous releases, and we don't want silent failures. For now, I don't think we are planning to support alternative front-end development, so we may not need to communicate extensively about what changes are being made and why, but if we want to be able to deploy breaking changes to the API without doing it in the middle of the night and praying nobody is running a 24-hour test center, we need the two pieces of software to be able to negotiate over some supported range of versions.
* from this it follows that the _when_ is any time we're adding something that might break the client by its presence or absence, which is... a lot, I would think.

**Comment by benwarfield-usds** [comment]
As far as external integrations go, I posit the following:

**CSV is a transport, not a format.**

Yes I know that is a nonsensical statement, but I wanted to draw attention to the following use-case mismatch: nobody wants "a CSV document," they want _the data_ in some form that allows them to import it into their preferred (or required) tools. That is, they want a specific type of data set, with a specific set of data fields and hopefully some promises of internal validity, and they're willing to accept it in MS-Excel-flavored CSV because that's the de facto standard for shipping data around in e-mails. So more sensically one might say that CSV is a file format but not a data format, but that wasn't as much fun to type. (In a pinch, of course, they're willing to accept the data in a CSV file with unknown headers and no guarantees of validity, and just grind their teeth while they process it in, but we're trying to avoid that use case, I assume.)

The outcome of this in my view is that we should expect to have multiple named export data formats, which may or may not all have CSV mappings. Those formats may themselves be versioned, but it's also entirely possible that the expansion will be largely horizontal rather than vertical: it seems much easier to imagine needing to maintain five different export formats simultaneously (with versioning to track minor formatting issues) than actually having a single export format iterate through five versions with the expectation that everybody will stop using the first four.

**Comment by pete-gov** [comment]
I'm going to move this back into the icebox and out of the current milestones as we're switching away from an API driven infrastructure during prototyping.

**Comment by switzersc-usds** [comment]
All great thoughts - thanks, y'all! Agreed on backing this up for now while we further develop the prototypes.
