### ISSUE TITLE
Upload CSV of New Patients (Initial Workflow)

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#54]
As a test site administrator, I want to add many patients at once to the app, so that they can be tested and I don't have to add them one at a time.

(checklist items are phrased with built in acceptance criteria, i.e. it's not complete until that action is verifiable)

**Step 1:**
- [x] Allow user to click upload CSV button, select a file, and upload it

**Step 2:**
- [x] prep positive test case CSV
- [x] prep negative test case CSVs
- [x] validate the CSV file versus schema
- [x] check for errors in the CSV (csv-error)
- [x] check for schema errors (schema-error)
- [x] check for existing patients with matching unique patient id (existing-update)
~- [ ] check for existing patient records that are a exact field match of core fields (existing-error)~
    ~- [ ] core fields TBD, start with all names + address + email?~
    - *This is overkill for prototype and can get a bit heavy, skipping*

**Step 3:**
- [x] Preview the records in UI
    - [x] Show the records that are good and will be added with positive indicator of some kind
    - [x] Show the records that caused an error and will not be added with negative indicator of some kind
        - [x] csv-error
        - [x] schema-error
        ~- [ ] existing-error~
    ~- [ ] Show the existing patient records that will be updated (existing-update)~
- [x] Ask for confirmation to proceed or to cancel out
~- [ ] Make sure canceling clears out all the variables~ *eh doesn't matter*

**Step 4:**
*Moved to separate issue since this is dependent on data handling implementation*
https://github.com/CDCgov/prime-central/issues/100

~**Step 5.**~
~- [ ] add automated tests for these cases (lots of work to do here, probably not worth doing until after we've standardized)~ *skipping tests / go-fast*

~**Additional Issues to Review:**~
~- [ ] using the patient ID as a key for the dynamic react items can cause errors if they're dupes in the same CSV, find a different way to do that (increment by place in array?)~
~- [ ] check for memory issues using large files due to possible cloning of variables~
*both of these might pop up at some point but aren't going to be initial deal breakers, can be dealt with in the real world or by sanitizing input*

### Moved styling to follow on ticket: https://github.com/CDCgov/prime-central/issues/98

UI: https://heather574841.invisionapp.com/console/PDI-10-14-2020-HM-ckg9uf825007z01yg6dgr93w1/ckg9uf8v4006t010i7pzc7ilh/play

**Comment by pete-gov** [comment]
Increased precision in original story tasks, broke them out into work units.

**Comment by pete-gov** [comment]
I implemented local processing of a test CSV with some very rudimentary javascript. Workflow is basically:

1. use an `<input>` of type `file` to choose the CSV, on change trigger a loadFile function
2. loadFile uses FileReader to pull in the file then uses [react-papaparse](https://react-papaparse.js.org/) to convert it to JSON, tracking initial errors on CSV processing
3. we then use [Ajv](https://ajv.js.org/) to validate each row of the JSON data against our JSON Schema
4. bad rows are removed from our data array and added to a separate data array with some basic error messaging

![csv-import](https://user-images.githubusercontent.com/51794651/96759781-7f873b80-13a6-11eb-9a41-f4db1dfbd3d6.gif)

### Issues with JSON Schema

I encountered a number of issues with the original JSON Schema I created for patients, and had to take some steps to deal with this initially:

1. Needed to move them somewhere I could import them
2. Needed to figure out how to import them, did a bad job with this
3. **probably better for these to be globally imported somewhere but I don't know how**
4. ajv threw unknown format errors with `date` and `email` - instead of tracking that down I just removed them
5. my generated faker.js CSV phone numbers didn't follow the same format I was looking for, need better schema regexp around that

### Issues with React

I spent two hours trying to figure out how to update a div with some content after the CSV was loaded (the stuff I'm showing in console.log) and I couldn't find anything that seemed to work within the framework of this particular app style. I'm sure I'm missing something stupid. Will need some help figuring that out at some point.

### Branch
https://github.com/CDCgov/prime-data-input-client/tree/54-Upload-CSV

**Comment by pete-gov** [comment]
@hmyers-cms / @willusds I've made some workflow changes if you want to take a gander. Basically, all potential errors will be calculated prior to the Preview state shown as Slide 3. This comes with a couple questions:

1. I'm tracking the errors in a way that requires displaying the "good" rows in one preview section and the "bad" rows/etc. in a separate preview section - they can't be displayed in-line matching the original CSV order. Is that ok, or does it need to be a 1:1 with the original CSV?

2. The actual CSV data we're adding is potentially MUCH larger than the mockup data. It won't fit as prettily as the mockup data. Thoughts on handling this? Show all of the data with a tiny font, allow side scrolling, extra key pieces, show as cards instead of table rows, etc.? (see below for example line of text)

```
patientID,patientLastName,patientFirstName,patientMiddleName,patientSuffix,patientRace,patientDOB,patientGender,patientEthnicity,patientStreet,patientStreet2,patientCity,patientCounty,patientState,patientZipCode,patientPhoneNumber,patientEmail,patientAge,employedInHealthcare,typeOfHealthcareProfessional,residentCongregateSetting,patientResidencyType
1fd65780-b8b3-46bb-8dab-0dfd5eb1df24,Deckow,Linwood,Madisyn,DVM,Borders,Tue Apr 07 2020 02:56:57 GMT-0400 (Eastern Daylight Time),Man,Supervisor,2252 Toy Rest,Apt. 479,Camrynview,Avon,NC,85988-6833,(507) 813-3117 x841,Craig_Daniel86@hotmail.com,118,YES,Plain,NO,olive
7ce044c7-9f70-4d6a-992a-1a1264fa515d,Mills,Hilda,Griffin,DDS,Investment,Sat Dec 28 2019 00:51:05 GMT-0500 (Eastern Standard Time),Two-spirit person,Fresh,123 Malachi Brooks,Apt. 165,East Ara,Borders,FL,79875-7254,539.766.2889 x0338,Wendell.Moen4@gmail.com,106,YES,Arizona,UNK - Unknown,Cheese
a1affd29-cfba-4c07-887b-65fa9471f7dd,Ratke,Addison,Hassan,Sr.,Cotton,Mon Aug 31 2020 23:33:35 GMT-0400 (Eastern Daylight Time),Cis,Branding,421 Leffler Views,Apt. 479,Port Karolann,Avon,NY,25989,1-458-986-2862 x0355,Florencio_King36@yahoo.com,42,UNK - Unknown,Cambridgeshire,YES,Table
ecc6da3a-8a48-4c1b-900e-ff47ee0fceea,McClure,Scot,Idell,II,Data,Thu Jun 25 2020 03:59:03 GMT-0400 (Eastern Daylight Time),Transexual Man,drive,37077 Gerlach Trace,Suite 024,West Kiara,Avon,WI,60046-8841,931.525.1288 x2473,Axel.Johnson55@yahoo.com,103,YES,Sleek,UNK - Unknown,Toys
f3d0d9e5-a9b9-4388-83a4-ffa25cc8a5f0,Doyle,Zackary,Brigitte,MD,extensible,Wed Apr 08 2020 01:27:15 GMT-0400 (Eastern Daylight Time),Cisgender,Integration,68227 Waldo Orchard,Apt. 444,Kassulkefurt,Buckinghamshire,MA,46199,1-834-314-8859 x132,Deanna_Cartwright5@hotmail.com,99,NO,Ariary,NO,connecting

**Comment by hmyers-cms** [comment]
1. Unless I'm misunderstanding, this description matches how it was mocked up, so I think that's okay.
2. I think we should allow horizontal scrolling. I wasn't sure what all the data was when I initially mocked it up, but this is a good point

**Comment by pete-gov** [comment]
re: 1 - Yeah, woops, sorry, this precisely matches the mockup (but is a change from the original ticket).  I didn't notice those were out of sync.

**Comment by pete-gov** [comment]
I think I've moved this as far as I can. You can add a CSV (rename the attached .txt as csv) and it will process it. Requires papaparse-react and ajv, as well as the json schema (rudimentary at the moment).

It reads the CSV, converts it to JSON, matches it against the JSON schema using AJV, then checks for duplicates, wrapping up all the errors into `jsonImport.badRows` and manually mapping the fields to the local `patients` object in redux (does NOT save it permanently).

[patients.txt](https://github.com/CDCgov/prime-central/files/5439702/patients.txt)

To do some basic testing, start by grabbing the above patients.txt and rename it to patients.csv or whatever. Navigate to `/organization/123/patients` and open your console then click "Browse" to find the patients.csv file. It will trigger immediately. The resulting parsing/validating/etc. all outputs to the console. Since the `patients` object is temporarily updated in memory you can navigate to Results and see all the new folks. 

You can then go back and re-upload the same CSV and see some of the duplicate warning messages to test that. On reload all the data will be lost from the store. 

I don't know how to get react to update windows with the output for review and prompt for confirmation.

**Comment by pete-gov** [comment]
I "stole" the modal method used for AOE and figured out how to update state from that and finally managed to proof of concept something happening after uploading the CSV.

It's worth noting that generating tables in React seems to be a fairly spicy thing, especially since we need dynamic fields based on the schemas for good stuff but also just general crap for bad stuff. Will have to experiment with that separately.

Also, the modal I implemented doesn't match the mockups but I think it makes more sense as it creates a "captive session" where the user has to proceed through the workflow or cancel out before interacting with the rest of the site. (also, uh, it was easier?)

![csv](https://user-images.githubusercontent.com/51794651/97457047-c5488480-190f-11eb-8d7c-a13b125e3a42.gif)

**Comment by hmyers-cms** [comment]
I'm fine w/ the Modal interaction rather than a separate screen. Easier = better, and the idea of them being "captive" before moving on makes sense to me. We can validate with users to see if this interaction makes sense for them and change later only if needed.

**Comment by pete-gov** [comment]
I've completed the core workflows on this ticket, though I'm sure at some point @sharmaneil or @dmethvin-gov is going to look at what I did and shake their head. All the checked sections have been implemented. The strikethrough sections have been removed during prototype but are worth noting for later.

I've separated follow on into two tickets:

#100 - to actually do something with this patient data, dependent on how we end up handling this (no point in writing temporary stuff here)

#98 - to handle styling and making it look pretty
