### ISSUE TITLE
[Master Story] Patient Data Ingest

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-central#6]
As an **Organization Administrator**, I need to populate **Patient Data** in our organization's Data Input data store. To do this, I want to *upload a CSV file* that I exported from my *organization's system of record.* 

This issue is the core summary of features for this story, and includes sub tasks (that aren't obviously subtasks) such as:

#11 - Define Prototype CSV structure for Ingest
#13 - Define Data Input Data Storage Schema

-----

From 10/06 MVP meeting

**Current needs**

- CSV import
  - Create template for import
  - Record management done in CSV
  - Patients have a uniqe ID from a system of record (ex: student ID number)
  - Records can be exported
  - Records are updated via CSV export/edit/re-import
- Records can be deduped
- Imported records are displayed in an index

**Important concerns**

- HHS compliance
- PII PHI

**Parking lot**

- Manual patient entry form
- Editing records within the app
- Patient self entry
  - w/code/ID generation (QR code, or similar)

**Comment by pete-usds** [comment]
My overall notes from the meeting, a bit chaotic:

Should start with Neil & Shelby clarifying what they want out of this meeting so we stay on target for them, I'm assuming it will be something like...

    define the various "users" for the mocks
    clarify the workflows tied to those users (who does what)
    work through page by page to clarify what is happening
    discuss alternatives due to eng limitations
    try to get enough detail so we can create some user stories and tasks to flesh this out 

Mockups:
https://primedatainput.invisionapp.com/console/PDI-10-6-2020-KSA-ckfxxtc1h0071012aewwdcpfl

Data Input Board:
https://github.com/CDCgov/prime-central/projects/1

Neil:

Would be helpful for the product as a whole for everyone to get on the same page about what is being worked on. Has started to implement some stuff but the mockups are changing.

Also would like to know what the designers need.

Would like to use the project boards on github.

Left a dozen or more comments on the mocks and have a dozen or more to add.

Katie: I have questions too, everyone probably has questions.

Katie: in terms of feedback we're looking for, feedback on feasibility, a couple things we're just throwing in there.

Q where to capture comments decisions discussions?

Drew: Maybe github issues?

Katie: Is there a certain type of feedback or issue better suited to capturing in github vs comments.

some discussion about that

Neil: In turns of tracking design to-dos, what are the preferred ways for design issues?

Drew: I personally quite like github issues and it would make sense to have it in one place. Maybe use tags? Design, engineering, etc.

Katie: like the idea of everything in one place

okay let's try rolling in github for a couple sprints, on to mockup review!

Test Queue view: The person administering a test or checking in a patient at a POC?
We've been using the word "test administrator" as the person administering the test, but it might mean something else? 
Alicia: an area to do more research on, but there's two options on how this could be used:
1) the person who checks in the patient and adds you to the queue
2) the person who is using the queue to do the test

"think about it like you come in for the test and the administrator is the person who checks you in AND records the result"
Rick possibly using the word "nurse"

option to scan QR code (button)
or search by name, DOB, or alpha ID

is the QR code good for MVP?
QR codes are new sexy

search bar: autocomplete is dangerous for PHI? possibly dangerous at some point
for MVP maybe just an alphanumeric id?
but people might forget it, still need a way to look them up
maybe just not build autocomplete, search pattern needs to protect privacy
probably something to ask lawyers and privacy people about
lots of discussion about autocomplete or not
if you're a bad actor and want to look up random people it shouldn't be easy

Shelby: I want to better understand how patient records get into this system to begin with? For the MVP is it just the staff entering it manually? do we have to have a page where patients fill out first?

Alicia: CSV upload is number one feature people are excited about. 
Administrator adding people in.

Health department wanted to make sure the names are correct.

Shelby: If we assume CSV upload, could be 10k or 5 records...  what is a useful search feature? Probably want ot have ways to identify patient based off the ways they'd be record in other systems, such as student id number, external identifiers like email, probably not a code that we generate. 

Presumption: did we agree MVP would be just CSV upload?
Alicia - assume a person's record is tied to a single location.

Neil: Assume this is at a university, when you say location you mean the "university" as a location or test sites in a university of which they can be many?

Alicia: Location = University

Rick: There's testing organization and actual testing facilities. Could have many CLIA numbers maybe? 

Alicia: haven't seen that yet but something we should probably ask about

Neil: thinking there might be multiple test sites, part of the flow might include which sites, but that feels like metadata for patient registration. what shelby and I were thinking was a "nurse" is associated with an organization.

define organization: multiple test sites, but all patient data shared between all test sites. not shared with other orgs

shouldn't be data shared across organizations



CSV as source of truth for us - other system that generates CSV is the system of record
CSV upload needs deduplication

pre-test survey: patient fills this out in advance to get a QR code


workflow to this point:

upload CSV
that includes id
search by id
uploading dupes get deduped 
Shelby does agree we should discuss if/when we can be a system of record.

Neil suggests storing changes separately in separate fields.

2-4 weeks, get by with CSV upload, download, etc.
as soon as possible should be building add/edit patients information

maybe it's easier to skip CSV? pete and shelby shaking their heads

how do typos/etc get fixed 
Neil: taking it back a little bit, editing feels like something that can cause problems later [something to think about later]
If this information doesn't go anywhere after we change it, or if changing it in our site creates problems, I don't see it as possible or feasible for an MVP.

Alicia wants to make alternate possible:

1. still upload by CSV to add data
2. add new CSV or add more data to CSV
3. way to disable/hide records - 

Katie: Bulk upload route, only getting information is system of record. 

Next steps:

Neil:
async on a million questions about the queue
set up time on Thursday

Shelby:
this changes how I've been thinking about the API resource design

**Comment by willusds** [comment]
Break out into individual tickets, Parking lot becomes icebox

**Comment by pete-gov** [comment]
These have now been broken out into individual tickets by Alicia, including stuff like #55 #54 #53 #56 etc.
