### ISSUE TITLE
Flesh out Data Definition/Schema Handling

### ISSUE THREAD

**Issue by pete-gov** [CDCgov/prime-central#64]
We've started parallel workstreams working with data schemas and I'm concerned we're going to run into conflicts if we don't flesh it out and agree on a way to manage this. To ensure we're not all handling things in our own way and diverging a bunch of data structures, I think we should agree on answers to the following:

## 1. Patient data schema should be defined in a single place, every piece of code working with this data should rely on the same definition file.

_Features that need a patient data schema include:_
* List patients
* Search for patient and add patient to queue
* See appointment queue
* Add Patient 
* Edit Patient
* Upload CSV
* ... more?

_Features that require **validation** of data fields include:_
* Add Patient
* Edit Patient
* Upload CSV

**No page should have a hard coded list of fields** unless it's a subset for specific reasons. Ideally, adding a field to the schema will add a field to every page that displays patient data. Any validation of a field should use the same underlying code and the same underlying control to validate that field.

_Output of this ticket:_

1. Agree on and implement a way to manage a data schema for all patient data
2. Agree on validation mechanisms or how to define validation mechanisms for data

**Comment by pete-gov** [comment]
Some things I can think of that we should agree on for every field include:

1. Is the field required?
2. Must the field be one of X pre-defined options?
3. Is there a format the field must follow? (i.e. number, string, boolean and more complex structures like email, regexp)
4. Can the field be an array of values also matching any of the above?
5. What's the friendly name for the field?
6. Field order in relation to other fields? Or at least section of a document? Maybe just use an ordered definition file?

**Comment by pete-gov** [comment]
Some possible helpers for this:

* https://github.com/jquense/yup "Dead simple object schema validation"
* https://joi.dev/ "the most powerful schema description language and data validator for JavaScript"
* https://validatejs.org/ "Validate.js provides a declarative way of validating javascript objects"
* https://github.com/diegohaz/schm "schm is a library for creating immutable, composable, parseable and validatable (yeah, many *ables) schemas in JavaScript and Node.js."
* https://ajv.js.org/ "another JSON schema validator"

Also possible that a lot of this is already being handled by some of the stuff Neil did behind the scenes and just needs to be hooked up?

One factor to consider is that whatever helper we use, it should be simple enough (if at all possible) for product/design to edit directly so we're not shuttling changes back and forth between an airtable.

**Comment by dmethvin-gov** [comment]
This seems like a good use for a [JSON Schema](https://json-schema.org/) and there are plenty of implementations in multiple languages. There are also [some programs](https://www.npmjs.com/package/csval) to directly validate CSV formats using JSON Schema.

**Comment by benwarfield-usds** [comment]
For the internals of the PDI project as a single code-base, would Typescript make it easier or harder to make this work?

**Comment by dmethvin-gov** [comment]
JSON Schema and Typescript pair well. JSON Schema validates the incoming data so that you know it conforms to the rules. Once inside the code, the Typescript ensures there aren't any mistakes like a typo of `color === "reed"` when you meant `color === "red"`. There are [libraries](https://www.npmjs.com/package/json-schema-to-typescript) to turn a JSON Schema into a Typescript definition so you can still have an authoritative point of truth for the data definition.

**Comment by sharmaneil** [comment]
I'm game to try out these. The frontend right now isn't in typescript, but we can introduce it in parts. 

I was thinking about using [Formik](https://formik.org/) once I actually start working on forms with more than a single input. It pairs with Yup for validation nicely. 

Haven't used either before tho; we tried in the assessment generator at some point but failed iirc (the app was too complicated for these tools to work correctly)

**Comment by pete-gov** [comment]
Neil pointed this out and I think it's pretty sweet looking: https://github.com/rjsf-team/react-jsonschema-form

**Comment by benwarfield-usds** [comment]
That's what US Forms System is based on—I suspect we do not want to replicate that from scratch for this project, though I'm prepared to be wrong. 😁

**Comment by pete-gov** [comment]
I'm going to move forward with trying out a JSON-Schema setup, possibly with ajv, for the CSV side of the house. If that turns out to be good enough to build on, cool - if someone comes up with something better, cool.

**Comment by dmethvin-gov** [comment]
Formik has its own state management (for just the form data) which makes it great for simpler apps because it's an all-in-one solution, but that conflicts with things like Redux or Mobx. If the app is just going to let users enter/edit values, validate them, and send the values somewhere else, Formik could be fine. If the app needs to be making logic decisions, calculations, or a dashboard from the data, you probably want generic state. We were in the latter category with Assessment Generator.

The issue with USFS and react-jsonschema-form is that it [doesn't do a very good job of abstracting or encapsulating things](https://github.com/usds/us-forms-system/issues/141#issuecomment-422113206). This is not just an RJSF problem but a malaise of the whole React ecosystem really, there are lots of useful pieces but they solve the problem using different opinionated technologies.  So you might build a project on React+Redux+SASS which means a library based on React+Mobx+Styled-Components is useless to your project.

**Comment by pete-gov** [comment]
In a conversation with Alicia this afternoon, it came up that different Organizations will want to customize their Schemas - and if we're using Schemas, this is a much easier feature to add. I think through Stage 2 prototyping we probably don't have to worry about this, but when we get to multiple organizations we may want to think about how to handle this.

I volunteered for early pilot phases that we could (I could) just manually create custom schemas for Organizations by hand.

**Comment by pete-gov** [comment]
Did I end up being the only person doing stuff with this during Sprint 2? 

Should I close this issue for now or move it back to To Do or...? If no one else is planning to adopt this then no reason to keep it open.

**Comment by sharmaneil** [comment]
I am still hesitant to generate UI form components from a schema, mostly because it can be difficult to add custom styles or conditional logic. Also, aside from US Forms System, the ecosystem of libraries that automatically convert jsonschema -> form inputs appears lacking in react, or doesn't have great traction compared to the non-schema based ones. @dmethvin-gov will know more, and I can be convinced otherwise.

All the cool kids seem to be using: https://react-hook-form.com/

I am very much for using schemas _for validation._

**Comment by dmethvin-gov** [comment]
JSON Schema is definitely a valuable tool for validation and API documentation, so it seems worthwhile for us to define it. However, it doesn't have enough information to let someone create a UI. US Forms System tried to solve that with a mashup of JSON Schema chunks paired with UI description chunks but as we developed examples I became increasingly convinced that wasn't a good way forward. It makes more sense to define the form inputs and field relationships in terms of a declarative spec and then generate the schema from that. 

One problem we ran into both with USFS and Assessment Generator was the abundance of business logic that ended up being embedded in React components. If the logic is unchanging that could be tolerable, but when it needs to change it then becomes difficult to do, especially if the logic is spread across multiple components. I can't tell whether that problem exists in this project, and maybe we don't know yet, which is probably an argument for not solving a problem that may not exist.

From what I can gather we're still in the phase of not knowing what we'll need but wanting to have it ASAP. I think it might be better to just build a MVP with the tools we can scrape together and plan to throw it away if things don't work out. Nothing wrong with that!

When using a data store like Redux and a set of USWDS form components like the ones Ben looked at, I'm not convinced any of the React form libraries add a lot of value.

**Comment by sharmaneil** [comment]
Cool! Sounds like we have some decisions?

### Decisions
- no auto-generation of UI based from a JSON schema
- use JSON schema for validation and documentation
- just wing UI form-creation for now; don't rely on libraries for the MVP. 
- pages *CAN* have a hardcoded list of fields

### TBD:
- figure out which validation library we want to use, or just pick one. Pete has a list: https://github.com/CDCgov/prime-central/issues/64#issuecomment-712163555
- kinda out of scope, but since we've been talking about it: do we converge between CMSDS and our homegrown components for the MVP? The css is slightly inconsistent, but I don't care enough to spend the time converging on one right now. Designers might think otherwise tho

**Comment by pete-gov** [comment]
Concur with all for now.

FYSA I used ajv to validate in the CSV upload portion here: https://github.com/CDCgov/prime-data-input-client/blob/main/frontend/src/app/patients/ManagePatients.jsx and found it functional and easy. See lines 15-16, followed by 59-78. 

Not sure sure if it's also easy to implement on the UI directly tough.

**Comment by benwarfield-usds** [comment]
I opened an issue on the client project to address converging UI libraries. I don't want to do anything we don't need to, but we may need to do this (depends if there's a cheaper fix for that checkmark bug and/or other bugs like it).

**Comment by benwarfield-usds** [comment]
On the schema stuff, I would like to have the internal data structures be less ad-hoc than they are, but the things I was doing did not appear to fit into the existing schema work, and I didn't want to make that a blocker, so I went ad-hoc. 

I think that we should probably have the UI for certain areas in the application be as configuration-driven as possible, and be open to the possibility of having that configuration be per-site—but I'm not sure how declarative it can get without just having the configuration be a new programming language.
